### ISSUE TITLE
Support for processing plain-text emails

### ISSUE THREAD

**Issue by jkupczak** [cossssmin/alter.email#1]
Would it be a good idea to add a toggle for transforming plain-text emails? I imagine it would get far less use, but plain-text emails would definitely benefit from the URL Parameters function and the Detergent function.

**Comment by cossssmin** [comment]
Hmm, I guess we could have a standalone option for that. 

Since a plaintext transformation can already be handled by `detergent` through the `stripHtml` option, this new option would simply toggle it. So it could be regarded as a duplicate, but the point would be to offer a better UI since now it's not clear where you go to generate plaintext, right?

Considering #8, what do you think about having a single "Formatting" tab to house `prettify`, `minify`, and `plaintext`?

**Comment by jkupczak** [comment]
So I think there's two things going on here.

**Idea #1**
My original intention was just to accommodate someone who is pasting in an original source of just plain text. This person is just looking for the URL parameters and detergent functions. I was thinking maybe we either detect that the source doesn't include HTML or ask them to specify their intent by selecting "Text Email". And then we simplify the UI by only surfacing the relevant transformers. We'd also update the preview panes to use `white-space: pre`.

**Idea #2**
Then there's the person who is looking to **generate** plain text from an HTML source they've provided, and possibly also transforming it using the previously mentioned transformers. Which I think is the direction you were suggesting?

Either way, I think these are both great ideas.

**Comment by cossssmin** [comment]
>  _accommodate someone who is pasting in an original source of just plain text [...] is just looking for the URL parameters and detergent functions_

I was indeed thinking about the second idea.

The tool is built specifically for HTML email, the URL parameters function won't work on plaintext - it needs to find anchor tags. This may change in the future, but for now 1 is not an option.
