### ISSUE TITLE
Bug: Code fails to be processed when using `Text Cleanup` option

### ISSUE THREAD

**Issue by jkupczak** [cossssmin/alter.email#9]
As mentioned in the emailgeeks Slack channel I get the following error when trying to transform code while `Text Cleanup` is turned on:

`POST https://alter.email/.netlify/functions/transform 502`

**Comment by cossssmin** [comment]
Yes, something is breaking when using the `removeWidows` option. 

Which is weird, because all options aside (turned off), it receives the exact same text you add in the "Input" editor - and that clearly works on [detergent.io](https://detergent.io). 

It throws a `string-remove-widows` TypeError - followed up with @revelt and he's looking into it.

**Comment by revelt** [comment]
Sorry everybody! It's already fixed on my local, will deploy the fix in the next day or so. That was courageous use of `String.trim()` and not checking is it string at the first place. Excuse was it was a callback...

**Comment by revelt** [comment]
Update deps and try now

**Comment by cossssmin** [comment]
Still not working, it's a `ranges-push` issue. As Roy said, it's either a Rollup configuration issue with that package, or Netlify lambda function compilation misconfigured or simply not supporting Classes.

Since not using transformers server-side is not an option, I'll have to remove the "Text Cleanup" functionality for now.
